//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesWeb.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produk
    {
        public int ProdukID { get; set; }
        public string Nama { get; set; }
        public Nullable<int> Harga { get; set; }
        public string Deskripsi { get; set; }
    }
}
