//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesWeb.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaksi
    {
        public int TransaksiID { get; set; }
        public string KodeTransaksi { get; set; }
        public Nullable<System.DateTime> Tanggal { get; set; }
        public Nullable<int> PelangganID { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
